name: Build e Push Docker

on:
  push:
    branches:
      - shared

env: 
  ECR_REPOSITORY: ecr-github-runner-build
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 817697649340
  ROLE_TO_ASSUME: arn:aws:iam::817697649340:role/teste-thaynafonseca-mytech

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: codebuild-prd-backend-api-${{ github.run_id }}-${{ github.run_attempt }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Assume Role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tags
        id: vars
        run: |
          IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
          IMAGE_TAG=${GITHUB_SHA}  

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_URI:$IMAGE_TAG -f Dockerfile .
          docker tag $IMAGE_URI:$IMAGE_TAG $IMAGE_URI:latest

      - name: Push image to ECR
        run: |
          docker push $IMAGE_URI:$IMAGE_TAG
          docker push $IMAGE_URI:latest
