name: Build e Push Docker

on:
  push:
    branches:
      - shared

env: 
  ecr_repository: ecr-github-runner-build
  aws_region: us-east-1
  aws_account_id: 817697649340
  role_to_assume: arn:aws:iam::817697649340:role/teste-thaynafonseca-mytech

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Assume Role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tags
        id: vars
        run: |
          IMAGE_URI=${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository }}
          IMAGE_TAG=${GITHUB_SHA}  

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_URI:$IMAGE_TAG -f Dockerfile .
          docker tag $IMAGE_URI:$IMAGE_TAG $IMAGE_URI:latest

      - name: Push image to ECR
        run: |
          docker push $IMAGE_URI:$IMAGE_TAG
          docker push $IMAGE_URI:latest
